[package]
authors     = ["Patrick Auernig <dev.patrick.auernig@gmail.com>"]
name        = "discord-rpc-client"
description = "A Rust client for Discord RPC."
keywords    = ["discord", "rpc", "ipc"]
license     = "MIT"
readme      = "README.md"
repository  = "https://gitlab.com/valeth/discord-rpc-client.rs.git"
version     = "0.1.5"

[badges]
# gitlab      = { repository = "valeth/discord-rpc-client.rs" }
travis-ci   = { repository = "valeth/discord-rpc-client.rs" }
maintenance = { status = "experimental" }

[dependencies]
serde        = "^1.0"
serde_derive = "^1.0"
serde_json   = "^1.0"
byteorder    = "^1.0"
log          = "~0.4"
libc         = "0.2.39" # until std::process::id is stable

[target.'cfg(windows)'.dependencies]
named_pipe   = "0.3.0"

[dependencies.uuid]
version  = "^0.6.2"
features = ["v4"]

[features]
default = ["rich_presence"]
rich_presence = []

# [workspace]
# members = ["examples/discord_presence"]
